export const dashData = [
  {
    customers: [
      { id: 1, title: "Users", icon: "users.svg", alt: "users" },
      { id: 2, title: "Guarantors", icon: "guarantors.svg", alt: "guarantors" },
      { id: 3, title: "Loans", icon: "sack.svg", alt: "sack" },
      {
        id: 4,
        title: "Decision Models",
        icon: "handshake.svg",
        alt: "handshake",
      },
      { id: 5, title: "Savings", icon: "piggy-bank.svg", alt: "piggy-bank" },
      { id: 6, title: "Loan Requests", icon: "request.svg", alt: "request" },
      { id: 7, title: "Whitelist", icon: "user-check.svg", alt: "user-check" },
      { id: 8, title: "Karma", icon: "user-times.svg", alt: "user-times" },
    ],
  },
  {
    businesses: [
      { id: 9, title: "Organization", icon: "briefcase.svg", alt: "briefcase" },
      { id: 10, title: "Loan Products", icon: "request.svg", alt: "request" },
      { id: 11, title: "Savings Products", icon: "bank.svg", alt: "bank" },
      {
        id: 12,
        title: "Fees and Charges",
        icon: "coins-solid.svg",
        alt: "coins-solid",
      },
      { id: 13, title: "Transactions", icon: "transact.svg", alt: "transact" },
      { id: 14, title: "Services", icon: "galaxy.svg", alt: "galaxy" },
      {
        id: 15,
        title: "Service Account",
        icon: "user-cog.svg",
        alt: "user-cog",
      },
      { id: 16, title: "Settlements", icon: "scroll.svg", alt: "scroll" },
      { id: 17, title: "Reports", icon: "chart-bar.svg", alt: "chart-bar" },
    ],
  },
  {
    settings: [
      { id: 18, title: "Preferences", icon: "sliders.svg", alt: "sliders" },
      {
        id: 19,
        title: "Fees and Pricing",
        icon: "badge-percent.svg",
        alt: "badge-percent",
      },
      {
        id: 20,
        title: "Audit Logs",
        icon: "clipboard-list.svg",
        alt: "clipboard-list",
      },
    ],
  },
  {
    main: [
      { id: 1, title: "USERS", icon: "user.svg", alt: "user", value: 2453 },
      {
        id: 2,
        title: "ACTIVE USERS",
        icon: "users-active.svg",
        alt: "active",
        value: 2453,
      },
      {
        id: 3,
        title: "USERS WITH LOANS",
        icon: "users-loans.svg",
        alt: "loans",
        value: 12453,
      },
      {
        id: 4,
        title: "USERS WITH SAVINGS",
        icon: "users-save.svg",
        alt: "save",
        value: 102453,
      },
    ],
  },
  {
    tableData: [
      {
        organisation: "Lendstar",
        username: "Adedeji",
        email: "adedeji@lendsqr.com",
        phone: "08078903721",
        date: "May 15, 2020 10:00 AM",
        status: "Inactive",
      },
      {
        organisation: "Irorun",
        username: "Debby Ogana",
        email: "debby2@irorun.com",
        phone: "08160780928",
        date: "Apr 30, 2020 10:00 AM",
        status: "Pending",
      },
      {
        organisation: "Lendstar",
        username: "Grace Effiom",
        email: "grace@lendstar.com",
        phone: "07060780922",
        date: "Apr 30, 2020 10:00 AM",
        status: "Blacklisted",
      },
      {
        organisation: "Lendstar",
        username: "Tosin Dokunmu",
        email: "tosin@lendsqr.com",
        phone: "07003309226",
        date: "Apr 10, 2020 10:00 AM",
        status: "Pending",
      },
      {
        organisation: "Lendstar",
        username: "Grace Effiom",
        email: "grace@lendstar.com",
        phone: "07060780922",
        date: "Apr 30, 2020 10:00 AM",
        status: "Active",
      },
      {
        organisation: "Lendsqr",
        username: "Tosin Dokunmu",
        email: "tosin@lendsqr.com",
        phone: "08060780900",
        date: "Apr 10, 2022 10:00 AM",
        status: "Active",
      },
      {
        organisation: "Lendstar",
        username: "Grace Effiom",
        email: "grace@lendstar.com",
        phone: "07060780922",
        date: "Apr 30, 2022 10:00 AM",
        status: "Blacklisted",
      },
      {
        organisation: "Lendsqr",
        username: "Tosin Dokunmu",
        email: "tosin@lendsqr.com",
        phone: "08060780900",
        date: "Apr 10, 2020 10:00 AM",
        status: "Inactive",
      },
      {
        organisation: "Lendstar",
        username: "Grace Effiom",
        email: "grace@lendstar.com",
        phone: "07060780922",
        date: "Apr 10, 2020 10:00 AM",
        status: "Inactive",
      },
    ],
  },
];
